name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

#  build:

#    runs-on: ubuntu-latest

#    steps:
#    - uses: actions/checkout@v3
#    - name: Log in to Docker Hub
#      uses: docker/login-action@v2.1.0
#      with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#    - name: Build the Docker image
#      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/dvsba:latest
#    - name: Push to Docker repository
#      run: docker push ${{secrets.DOCKER_USERNAME}}/dvsba:latest
      
  deploy:
  
    runs-on: ubuntu-latest
    steps:
    - name: Run docker image
      run: docker run -d -p 8080:8080 viswasringan/dvsba:latest
    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.7.0
      with:
          docker_name: owasp/zap2docker-stable
          target: http://127.0.0.1:8080/
          cmd_options: 'I'
